FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["WeCore.UI/WeCore.UI.csproj", "WeCore.UI/"]
COPY ["WeCore.sln", "./"]
RUN dotnet restore "WeCore.UI/WeCore.UI.csproj"

COPY . .
RUN dotnet publish "WeCore.UI/WeCore.UI.csproj" -c Release -o /app/publish

FROM nginx:alpine
WORKDIR /usr/share/nginx/html
COPY --from=build /app/publish/wwwroot .
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
